[package]
name = "strings"
version = "0.1.0"
authors = ["Lord-sarcastic <adeoti.15.jude@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
